'use client'

import React from 'react'
import {
  Calendar,
  Clock,
  MapPin,
  Sparkles,
  Heart,
  Gift,
  Wine,
  Shirt,
  Music,
  Camera,
  Info,
  Car,
  Building2,
  Award,
  Landmark,
  Bell,
  Utensils,
  Plane,
  Gem,
  Check,
  Star,
  Users,
  MessageSquare,
  Link as LinkIcon,
  Globe,
  Video,
  ShoppingBag,
  Feather,
  Quote,
  Image as ImageIcon,
  Cake,
  PartyPopper,
  Flame,
  Baby,
  Sun,
  Beer,
  Crown,
  Flower2,
  Bus,
  Coffee,
  GlassWater,
  Trophy,
  Mic,
  Headphones,
  Compass,
  QrCode,
  Phone,
  Mail,
  DollarSign,
  Wallet,
  Umbrella,
  Watch,
  TreePine,
  Moon,
  Gamepad2,
  Smile,
  ShieldCheck,
  Infinity,
  Sparkle,
  LucideIcon,
} from 'lucide-react'
import { NombreIcono } from '@/types/invitation'

export interface IconoInfo {
  id: NombreIcono
  etiqueta: string
}

export const LISTA_ICONOS_DISPONIBLES: IconoInfo[] = [
  // Celebración y fiesta
  { id: 'cake', etiqueta: 'Torta / Cumpleaños' },
  { id: 'partyPopper', etiqueta: 'Fiesta / Confeti' },
  { id: 'sparkles', etiqueta: 'Celebración & Destellos' },
  { id: 'sparkle', etiqueta: 'Brillo Mágico' },
  { id: 'crown', etiqueta: 'Corona / Quinceañera / VIP' },
  { id: 'trophy', etiqueta: 'Trofeo / Premiación / Logro' },
  { id: 'music', etiqueta: 'Música / Baile' },
  { id: 'headphones', etiqueta: 'DJ / Fiesta Sound' },
  { id: 'mic', etiqueta: 'Micrófono / Brindis / Show' },
  { id: 'gamepad', etiqueta: 'Videojuegos / Recreación' },

  // Romance, bodas y amor
  { id: 'heart', etiqueta: 'Amor / Pareja' },
  { id: 'ring', etiqueta: 'Anillos / Alianza Matrimonial' },
  { id: 'infinity', etiqueta: 'Amor Eterno / Aniversario' },
  { id: 'church', etiqueta: 'Templo / Parroquia' },
  { id: 'bell', etiqueta: 'Campanas / Ceremonia' },
  { id: 'feather', etiqueta: 'Votos Nupciales / Poema' },

  // Comida, brindis y gastronomía
  { id: 'wine', etiqueta: 'Copas / Vino / Cóctel de Bienvenida' },
  { id: 'cocktail', etiqueta: 'Trago / Coctelería / Brindis' },
  { id: 'beer', etiqueta: 'Cerveza / Barra Libre' },
  { id: 'utensils', etiqueta: 'Banquete / Menú / Cena' },
  { id: 'coffee', etiqueta: 'Café / Brunch / Tarde de Té' },
  { id: 'flame', etiqueta: 'Asado / Parrilla / BBQ' },

  // Familia, naturaleza y temáticas
  { id: 'baby', etiqueta: 'Bebé / Bautizo / Baby Shower' },
  { id: 'smile', etiqueta: 'Sonrisa / Niños / Familiar' },
  { id: 'sun', etiqueta: 'Sol / Fiesta de Día / Piscina' },
  { id: 'moon', etiqueta: 'Noche / Fiesta Bajo la Luna' },
  { id: 'flower', etiqueta: 'Flores / Decoración Floral' },
  { id: 'tree', etiqueta: 'Finca / Campo / Jardín' },

  // Logística, transporte y acceso
  { id: 'calendar', etiqueta: 'Fecha / Calendario' },
  { id: 'clock', etiqueta: 'Hora / Puntualidad' },
  { id: 'watch', etiqueta: 'Cronograma' },
  { id: 'mapPin', etiqueta: 'Ubicación / Mapa' },
  { id: 'compass', etiqueta: 'Cómo Llegar / Coordenadas' },
  { id: 'building', etiqueta: 'Hotel / Salón de Recepciones' },
  { id: 'car', etiqueta: 'Parqueadero / Valet Parking' },
  { id: 'bus', etiqueta: 'Transporte de Invitados' },
  { id: 'plane', etiqueta: 'Viaje / Evento Destino' },
  { id: 'qrCode', etiqueta: 'Pase Digital / Código QR' },
  { id: 'shieldCheck', etiqueta: 'Acceso VIP / Seguridad' },

  // Regalos, etiqueta y contacto
  { id: 'gift', etiqueta: 'Lluvia de Sobres / Regalos' },
  { id: 'wallet', etiqueta: 'Billetera / Sobre Digital' },
  { id: 'dollarSign', etiqueta: 'Cuenta Bancaria / Transferencia' },
  { id: 'shoppingBag', etiqueta: 'Lista de Bodas / Tienda' },
  { id: 'shirt', etiqueta: 'Dress Code / Vestimenta' },
  { id: 'umbrella', etiqueta: 'Clima / Recomendación de Ropa' },
  { id: 'camera', etiqueta: 'Fotografía / Hashtag' },
  { id: 'video', etiqueta: 'Transmisión Online / Streaming' },
  { id: 'phone', etiqueta: 'Teléfono de Contacto' },
  { id: 'mail', etiqueta: 'Correo Electrónico' },
  { id: 'messageSquare', etiqueta: 'WhatsApp / Chat RSVP' },
  { id: 'users', etiqueta: 'Lista de Asistentes' },
  { id: 'quote', etiqueta: 'Frase o Cita Inspiradora' },
  { id: 'award', etiqueta: 'Grado Académico / Condecoración' },
  { id: 'star', etiqueta: 'Aviso Importante' },
  { id: 'info', etiqueta: 'Información Adicional' },
  { id: 'link', etiqueta: 'Enlace Web' },
  { id: 'globe', etiqueta: 'Página Web Oficial' },
  { id: 'image', etiqueta: 'Galería de Fotos' },
  { id: 'check', etiqueta: 'Confirmado / Listo' },
]

const MAPA_ICONOS: Record<NombreIcono, LucideIcon> = {
  calendar: Calendar,
  clock: Clock,
  mapPin: MapPin,
  sparkles: Sparkles,
  heart: Heart,
  ring: Gem,
  wine: Wine,
  utensils: Utensils,
  music: Music,
  shirt: Shirt,
  gift: Gift,
  camera: Camera,
  building: Building2,
  church: Landmark,
  car: Car,
  plane: Plane,
  award: Award,
  bell: Bell,
  star: Star,
  users: Users,
  messageSquare: MessageSquare,
  info: Info,
  check: Check,
  feather: Feather,
  quote: Quote,
  link: LinkIcon,
  globe: Globe,
  video: Video,
  shoppingBag: ShoppingBag,
  image: ImageIcon,
  cake: Cake,
  partyPopper: PartyPopper,
  flame: Flame,
  baby: Baby,
  sun: Sun,
  beer: Beer,
  crown: Crown,
  flower: Flower2,
  bus: Bus,
  coffee: Coffee,
  cocktail: GlassWater,
  trophy: Trophy,
  mic: Mic,
  headphones: Headphones,
  compass: Compass,
  qrCode: QrCode,
  phone: Phone,
  mail: Mail,
  dollarSign: DollarSign,
  wallet: Wallet,
  umbrella: Umbrella,
  watch: Watch,
  tree: TreePine,
  moon: Moon,
  gamepad: Gamepad2,
  smile: Smile,
  shieldCheck: ShieldCheck,
  infinity: Infinity,
  sparkle: Sparkle,
}

interface IconoDinamicoProps {
  nombre?: NombreIcono
  size?: number
  className?: string
  style?: React.CSSProperties
}

export function IconoDinamico({
  nombre = 'sparkles',
  size = 16,
  className = '',
  style,
}: IconoDinamicoProps) {
  const IconoComponente = MAPA_ICONOS[nombre] || Sparkles
  return <IconoComponente size={size} className={className} style={style} />
}
